modLoader = "javafml"
loaderVersion = "[45,)"
license = "Terrarium Licence"
issueTrackerURL = "https://github.com/terrarium-earth/${github_name}/issues"

[[mods]]
    modId = "stitch"
    version = "${version}"
    displayName = "Stitch"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/stitch"
    logoFile = "icon.png"
    authors = ""
    credits = ""
    description = ""

[[dependencies.stitch]]
    modId = "forge"
    mandatory = true
    versionRange = "[45,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.stitch]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,)"
    ordering = "NONE"
    side = "BOTH"