modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/athena/issues"

[[mods]]
    modId = "athena"
    version = "${version}"
    displayName = "Athena"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/athena"
    logoFile = "icon.png"
    authors = "ThatGravyBoat"
    credits = ""
    description = "Crossplatform Baked Model Loader"

[[dependencies.athena]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.athena]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,)"
    ordering = "NONE"
    side = "BOTH"